apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-10-28T20:33:45Z"
  labels:
    run: nginx
  name: nginx
  namespace: giropops
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
  dnsPolicy: ClusterFirst

